import express from "express";
import { createBlog } from "../controllers/blog/create.js";
import fetchBlogs from "../controllers/blog/fetchBlogs.js";
import fetchBlogById from "../controllers/blog/fetchBlogById.js";
import { updateBlog } from "../controllers/blog/update.js";
import { deleteBlog } from "../controllers/blog/delete.js";
const router = express.Router();
router.post("/create", createBlog);
router.get("/fetch", fetchBlogs);
router.get("/details/:id", fetchBlogById);
router.put("/update/:id", updateBlog);
router.delete("/delete/:id", deleteBlog);
export default router;
